### ISSUE TITLE
Автовыделение кода "Критерий"

### ISSUE THREAD

**Issue by SardorSharipov** [Xapulc/ABnTester#1]
Было бы круто если бы можно было выделять код в блоке "Критерий" какой то горячей клавишей.
Например, для пользователь Windows Ctrl + A, либо добавить иконку копирования
А то пытаешься выделить, а там все что не код тоже выделяется(
Это совсем не критично если что

**Comment by Ulya0302** [comment]
Привет! Добавили кнопку копирования в блок с кодом)
